"""
ID3 Decision Tree Implementation for PopOut

Adapted from the Connect Four ID3 implementation
Learns decision trees from PopOut game data generated by MCTS
"""

import pandas as pd
import numpy as np
import math
from collections import Counter
import csv
import os
import random

def train_test_split_manual(df, test_size=0.2, random_state=42):
    """Manual implementation of train_test_split"""
    np.random.seed(random_state)
    indices = list(df.index)
    np.random.shuffle(indices)

    test_size = int(len(indices) * test_size)
    test_indices = indices[:test_size]
    train_indices = indices[test_size:]

    return df.loc[train_indices], df.loc[test_indices]

# File paths
SCRIPT_DIR   = os.path.dirname(os.path.abspath(__file__))
DATA_DIR     = os.path.join(SCRIPT_DIR, 'data')
DATASET_FILE = os.path.join(DATA_DIR, 'popout_pairs.csv')
TREE_FILE    = os.path.join(DATA_DIR, 'popout_tree.json')

def entropy(values):
    """
    Calculate entropy of a list of values

    Args:
        values: List of class values or pandas Series

    Returns:
        Entropy value
    """
    if hasattr(values, 'empty') and values.empty:
        return 0

    if hasattr(values, 'tolist'):
        values = values.tolist()

    if not values:
        return 0

    total = len(values)
    counts = Counter(values)

    entropy = 0
    for count in counts.values():
        if count > 0:
            probability = count / total
            entropy -= probability * math.log2(probability)

    return entropy

def information_gain(dataset, attribute, target_attr):
    """
    Calculate information gain for splitting on an attribute

    Args:
        dataset: pandas DataFrame
        attribute: column name to split on
        target_attr: target column name

    Returns:
        Information gain value
    """
    total_entropy = entropy(dataset[target_attr])

    # Calculate weighted entropy after split
    weighted_entropy = 0
    total_samples = len(dataset)

    for value in dataset[attribute].unique():
        subset = dataset[dataset[attribute] == value]
        if len(subset) > 0:
            weight = len(subset) / total_samples
            subset_entropy = entropy(subset[target_attr])
            weighted_entropy += weight * subset_entropy

    return total_entropy - weighted_entropy

def id3(dataset, attributes, target_attr, max_depth=None, min_samples_split=2, depth=0):
    """
    Build ID3 decision tree recursively

    Args:
        dataset: Training data (pandas DataFrame)
        attributes: List of attribute names to consider for splitting
        target_attr: Target attribute name
        max_depth: Maximum tree depth (None for unlimited)
        min_samples_split: Minimum samples to split
        depth: Current depth

    Returns:
        Decision tree (nested dict) or leaf value
    """
    # Check stopping conditions
    if len(dataset) < min_samples_split:
        return Counter(dataset[target_attr]).most_common(1)[0][0]

    if max_depth is not None and depth >= max_depth:
        return Counter(dataset[target_attr]).most_common(1)[0][0]

    # Check if all samples have same class
    target_values = dataset[target_attr].unique()
    if len(target_values) == 1:
        return target_values[0]

    # Check if no attributes left
    if not attributes:
        return Counter(dataset[target_attr]).most_common(1)[0][0]

    # Find best attribute to split on
    best_attr = max(attributes, key=lambda attr: information_gain(dataset, attr, target_attr))
    best_gain = information_gain(dataset, best_attr, target_attr)

    # If no information gain, return majority class
    if best_gain == 0:
        return Counter(dataset[target_attr]).most_common(1)[0][0]

    # Create subtree
    tree = {best_attr: {}}
    remaining_attrs = [attr for attr in attributes if attr != best_attr]

    for value in dataset[best_attr].unique():
        subset = dataset[dataset[best_attr] == value]
        if len(subset) == 0:
            # No samples for this value, use majority class
            tree[best_attr][value] = Counter(dataset[target_attr]).most_common(1)[0][0]
        else:
            tree[best_attr][value] = id3(subset, remaining_attrs, target_attr,
                                       max_depth, min_samples_split, depth + 1)

    return tree

def predict_sample(tree, sample):
    """
    Predict class for a single sample using the decision tree

    Args:
        tree: Decision tree (dict or leaf value)
        sample: Sample dict with attribute values

    Returns:
        Predicted class
    """
    if not isinstance(tree, dict):
        return tree

    # Get root attribute
    root_attr = next(iter(tree))

    # Get value of root attribute in sample
    if root_attr not in sample:
        # Attribute not in sample, return most common class from training
        return "unknown"

    attr_value = sample[root_attr]

    # Check if this value exists in tree
    if attr_value not in tree[root_attr]:
        return "unknown"

    # Recurse down the tree
    subtree = tree[root_attr][attr_value]
    return predict_sample(subtree, sample)

def predict(tree, test_data):
    """
    Predict classes for multiple samples

    Args:
        tree: Decision tree
        test_data: pandas DataFrame with test samples

    Returns:
        List of predictions
    """
    predictions = []
    for _, sample in test_data.iterrows():
        pred = predict_sample(tree, sample.to_dict())
        predictions.append(pred)
    return predictions

def load_popout_data(filename=DATASET_FILE):
    """
    Load PopOut dataset from CSV

    Args:
        filename: CSV file path

    Returns:
        pandas DataFrame
    """
    if not os.path.exists(filename):
        print(f"Dataset file {filename} not found!")
        return None

    df = pd.read_csv(filename)

    # Convert board positions to strings for categorical treatment
    board_cols = [f'c{i}' for i in range(42)]
    for col in board_cols:
        df[col] = df[col].astype(str)

    return df

def train_popout_tree(dataset, max_depth=None, min_samples_split=2):
    """
    Train decision tree on PopOut dataset

    Args:
        dataset: Training data (pandas DataFrame)
        max_depth: Maximum tree depth
        min_samples_split: Minimum samples per split

    Returns:
        Trained decision tree
    """
    if dataset is None or len(dataset) == 0:
        print("No dataset available for training!")
        return None

    # Features: board positions c0-c41
    features = [f'c{i}' for i in range(42)]

    # Target: move_type (0=drop, 1=pop)
    target = 'move_type'

    print(f"Training tree with {len(dataset)} samples...")
    print(f"Features: {len(features)} board positions")
    print(f"Target: {target}")

    tree = id3(dataset, features, target, max_depth, min_samples_split)

    print("Tree training completed!")
    return tree

def evaluate_tree(tree, test_data):
    """
    Evaluate decision tree on test data

    Args:
        tree: Trained decision tree
        test_data: Test dataset (pandas DataFrame)

    Returns:
        Accuracy score
    """
    if tree is None or test_data is None or len(test_data) == 0:
        return 0.0

    predictions = predict(tree, test_data)
    actual = test_data['move_type'].tolist()

    correct = sum(1 for pred, act in zip(predictions, actual) if pred == act)
    accuracy = correct / len(actual)

    return accuracy

def save_tree(tree, filename=TREE_FILE):
    """
    Save decision tree to JSON file

    Args:
        tree: Decision tree dict
        filename: Output filename
    """
    import json
    import numpy as np

    class NumpyEncoder(json.JSONEncoder):
        """Custom encoder to handle numpy types from pandas."""
        def default(self, obj):
            if isinstance(obj, (np.integer,)):
                return int(obj)
            if isinstance(obj, (np.floating,)):
                return float(obj)
            return super().default(obj)

    with open(filename, 'w') as f:
        json.dump(tree, f, indent=2, cls=NumpyEncoder)

    print(f"Tree saved to {filename}")

def load_tree(filename=TREE_FILE):
    """
    Load decision tree from JSON file

    Args:
        filename: JSON filename

    Returns:
        Decision tree dict or None
    """
    import json

    if not os.path.exists(filename):
        print(f"Tree file {filename} not found!")
        return None

    with open(filename, 'r') as f:
        tree = json.load(f)

    print(f"Tree loaded from {filename}")
    return tree

def analyze_tree(tree, dataset):
    """
    Analyze the decision tree structure

    Args:
        tree: Decision tree
        dataset: Training dataset
    """
    def count_nodes(tree):
        if not isinstance(tree, dict):
            return 1, 0  # leaf, internal

        internal = 1
        leaves = 0

        root_attr = next(iter(tree))
        for subtree in tree[root_attr].values():
            l, i = count_nodes(subtree)
            leaves += l
            internal += i

        return leaves, internal

    leaves, internal = count_nodes(tree)
    total_nodes = leaves + internal

    print("\nTree Analysis:")
    print(f"Total nodes: {total_nodes}")
    print(f"Internal nodes: {internal}")
    print(f"Leaf nodes: {leaves}")
    print(f"Leaf ratio: {leaves/total_nodes*100:.1f}%")

    # Most important features (root and early splits)
    def get_feature_usage(tree, depth=0, max_depth=3):
        if not isinstance(tree, dict) or depth >= max_depth:
            return {}

        root_attr = next(iter(tree))
        usage = {root_attr: 1}  # Initialize usage dict

        for subtree in tree[root_attr].values():
            sub_usage = get_feature_usage(subtree, depth + 1, max_depth)
            for attr, count in sub_usage.items():
                usage[attr] = usage.get(attr, 0) + count

        return usage

    feature_usage = get_feature_usage(tree)
    print("\nTop features used in tree:")
    sorted_features = sorted(feature_usage.items(), key=lambda x: x[1], reverse=True)
    for feature, count in sorted_features[:10]:
        print(f"  {feature}: used {count} times")

if __name__ == "__main__":
    print("PopOut ID3 Decision Tree")
    print("=" * 40)

    # Load dataset
    print("Loading dataset...")
    dataset = load_popout_data()

    if dataset is None:
        print("Cannot proceed without dataset!")
        exit(1)

    print(f"Dataset loaded: {len(dataset)} samples")
    print(f"Columns: {list(dataset.columns)}")

    # Analyze class distribution
    move_types = dataset['move_type'].value_counts()
    print("\nMove type distribution:")
    print(f"Drop (0): {move_types.get(0, 0)} samples ({move_types.get(0, 0)/len(dataset)*100:.1f}%)")
    print(f"Pop (1): {move_types.get(1, 0)} samples ({move_types.get(1, 0)/len(dataset)*100:.1f}%)")

    # Split into train/test
    train_data, test_data = train_test_split_manual(dataset, test_size=0.2, random_state=42)

    print(f"\nTraining set: {len(train_data)} samples")
    print(f"Test set: {len(test_data)} samples")

    # Train tree
    tree = train_popout_tree(train_data, max_depth=10)

    if tree is None:
        print("Tree training failed!")
        exit(1)

    # Evaluate tree
    train_accuracy = evaluate_tree(tree, train_data)
    test_accuracy = evaluate_tree(tree, test_data)

    print(f"\nTraining accuracy: {train_accuracy*100:.1f}%")
    print(f"Test accuracy: {test_accuracy*100:.1f}%")

    # Analyze tree
    analyze_tree(tree, train_data)

    # Save tree
    save_tree(tree)

    print("\nID3 training completed!")